version: '3.8'

networks:
  questionnaire-network:
    driver: bridge

services:
  app:
    build: .
    container_name: questionnaire-app
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./config.json:/root/config.json
      - app_uploads:/root/pkg/data/uploads
    networks:
      - questionnaire-network

  mysql:
    image: mysql:latest
    container_name: questionnaire-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: questionnaire
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-ppassword", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - questionnaire-network

  redis:
    image: redis:latest
    container_name: questionnaire-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - questionnaire-network

volumes:
  mysql_data:
  redis_data:
  app_uploads: